[build]
  base = "fashion-store/fashion-store"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "http://*theauralifestyle.org/*"
  to = "https://theauralifestyle.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.theauralifestyle.org/*"
  to = "https://theauralifestyle.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
